strfasd = "aasdasdasdasdsgj,kljsfgklsdfgsdfg
fdsfsd
gsffasfdf
gsdffasasdfd
gasdasdfasd
sdfgasdff
dfgasdklaasdfsghdkljashdjkf adhlfjkadasdfasdf
sdfggsdfsddfasdfasdfasd
gf
dfasdggddfgdfgsdfgsdfgsdf
g"fsd
fasdfasdfasdfkljsdfhlsdjfhlskdjfhasdjklfhasdjklfhasjklfhasdfasdfsdfasd
print(str)gdfgsdfgdfgsdfgsdfgsdfgsdfgsdfgsdfgsdfgsdfgsdfgsdfgsdfgfasdfsdafsfasdfsdfasdfsdfsdlkfhasdlkfjasdhlkfjhasdkljfasdhlfs
